lint: {}
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: Igiraneza Clement, Bilal Asser, Firas Zemzem, more tbc
  description: A profile-based pipeline for genomic epidemiological analysis of predefined
    pathogens.
  force: false
  is_nfcore: true
  name: pathogenepidemiology
  org: nf-core
  outdir: .
  version: 0.1.0dev
